### PR TITLE
add keybindings: prev_output, prev_output_with_win

### LINKED ISSUE #2071: Allow keybindings to move to the previous output
The plugin oswitch only supports `next_output` and `next_output_with_win`. This is convenient enough with a 2 monitors setup. 
However if you have 3 or more monitors, it is not that convenient as you have to iterate through all monitors to get to the target one, if you only use keyboard.
Thus there's a demand for `prev_output` and `prev_output_with_win` in this case.

### PR DESCRIPTION
**Pull request by A7R7**
provide an api `wf::output_t *get_prev_output(wf::output_t *output)` in core/output-layout.hpp
and use this api to implement `prev_output` and `prev_output_with_win`
fixes #2071

### CODE REVIEW

**Comment by A7R7** [comment]
Haven't noticed there's already #1570. I may take up his work then

**Review by ammen99 — CHANGES_REQUESTED** [review]
As mentioned in the other PR (#1570) there are two changes needed:

- The get_prev_output() shouldn't be added to core at all, oswitch can do that on its own.
- It would be nice to refactor the code so that the functions for next and previous output reuse the same code. Currently, they do the exact same thing but with the only difference of previous/next output. I imagine it should be easy to refactor them to use a common function `switch_to_output(target_output)` and `switch_to_output_with_window(target_output)`

**Comment by A7R7** [comment]
I did some refactor to the original functions, most importantly add `get_output_relative` to get the target monitor instead of changing the core api. The 4 activator_callbacks now only use `switch_to_output(target_output)` and `switch_to_output_with_window(target_output)` to finish their jobs.

I haven't implement `swap_output` and `swap_output_prev` in #1570, because I'm not sure if it is better to swap only the top view or swap the whole active workspace on the 2 outputs, or if it is good to add both functionalities (which I think will be a little mess).

**Comment by ammen99** [comment]
> I haven't implement `swap_output` and `swap_output_prev` in #1570, because I'm not sure if it is better to swap only the top view or swap the whole active workspace on the 2 outputs, or if it is good to add both functionalities (which I think will be a little mess).

That is fine, since you are doing the work, you can only add whatever you find useful :)

**Review by ammen99 — APPROVED** [review]
LGTM now, thanks!

**Comment by ammen99** [comment]
Please fix code style as well (there is a diff in the CI logs)

**Comment by A7R7** [comment]
I've fixed the code style with your fork of  uncrustify, hopefully it can pass!

**Pull request merged**
