### PR TITLE
xdg-shell: fix potential crash with inert popups

### LINKED ISSUE #2445: Random crash in wayfire_foreign_toplevel::init_request_handlers() (race condition with xdg-popups?)
**Describe the bug**
This happened once randomly while I was experimenting in follow up to #2422 -- Wayfire crashed while clicking on an icon with a subdock in Cairo-Dock. My hunch is that this is a race condition with xdg-popups similar to #772 but in this case Wayfire trying to use an "inert" popup (more detailed reasoning below).

**To Reproduce**
So far I cannot actually reproduce, which is not surprising, since it is likely extremely sensitive to timing, and I've already been using the equivalent setup for ~2-3 years without issues. I do have an idea how to write a reproducible example based on my previous experience with similar race conditions e.g. [this](https://github.com/dkondor/wlroots/blob/issue-2432/issue-2432/wlr-crasher.c) and [this](https://github.com/dkondor/egl_popup_test). Once I have a bit more time, I can experiment with this.

What I did the time it happened:
1. Start Cairo-Dock ([beta version](https://github.com/Cairo-Dock/cairo-dock-core)) and also [this](https://github.com/dkondor/wayfire-scale-ipc) plugin (note: based on my previous experience, any other interaction that triggers a close of a subdock at the wrong time should also work).
2. Open at least two instances of an app (so they are grouped into a subdock)
3. Click the corresponding icon.

**Expected behavior**
Scale is started showing only the views of the selected app. The corresponding subdock might appear as you move the mouse over the icon, and it might be closed once scale starts.

**Screenshots or stacktrace**
This is from the syslog and unfortunately I don't have debug info enabled:
```
Aug 24 12:30:25 thinkpad-x230 wayfire[2351]: II 24-08-24 12:30:25.053 - [src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface:  app-id: sakura
Aug 24 12:30:25 thinkpad-x230 systemd[2109]: Started vte-spawn-6d04869b-f1bd-42b2-979d-8bd17ba5b16e.scope - VTE child process 3331 launched by sakura process 3323.
Aug 24 12:30:26 thinkpad-x230 wayfire[2351]: II 24-08-24 12:30:26.118 - [src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface:  app-id: sakura
Aug 24 12:30:26 thinkpad-x230 systemd[2109]: Started vte-spawn-98c67524-bf95-4b5e-b2d5-ea8498e0414e.scope - VTE child process 3353 launched by sakura process 3345.
Aug 24 12:30:26 thinkpad-x230 wayfire[2351]: II 24-08-24 12:30:26.141 - [src/view/xdg-shell.cpp:124] New xdg popup
Aug 24 12:30:26 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:26.141 - [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5a47d57ede60
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: II 24-08-24 12:30:30.016 - [src/view/xdg-shell.cpp:124] New xdg popup
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.016 - [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5a47d5827870
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.030 - [src/main.cpp:141] Fatal error: Segmentation fault
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.068 - #1  signal_handler(int) main.cpp:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.652 - #2  __restore_rt libc_sigaction.c:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.666 - #3  wayfire_foreign_toplevel::init_request_handlers()::{lambda(void*)#3}::operator()(void*) const ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.684 - #4  wf::wl_listener_wrapper::emit(void*) ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.700 - #5  wl_signal_emit_mutable ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.717 - #6  foreign_toplevel_handle_set_rectangle wlr_foreign_toplevel_management_v1.c:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.730 - #7  ffi_prep_go_closure ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.745 - #8  ?? ??:0
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.756 - #9  ffi_call ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.770 - #10 ?? ??:0
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.784 - #11 wl_array_add ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.798 - #12 wl_event_loop_dispatch ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.814 - #13 wl_display_run ??:?
Aug 24 12:30:30 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:30.835 - #14 main ??:?
Aug 24 12:30:31 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:31.020 - #15 __libc_start_call_main ../sysdeps/x86/libc-start.c:74
Aug 24 12:30:31 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:31.207 - #16 call_init ../csu/libc-start.c:128
Aug 24 12:30:31 thinkpad-x230 wayfire[2351]: EE 24-08-24 12:30:31.229 - #17 _start ??:?
```

**Wayfire version**
git (44e1fa9c62e1f8c9f35cedbf3e86c6a0247e0b79)

**What I think happens**
1. With the mouse pointing to an icon that represents multiple instances (multiple open views) of an app, CD will open a subdock, which is an xdg-popup (BTW I'm aware this is not a very good design choice, but changing it will take some work; however, it should not trigger a crash in the compositor)
2. CD will send [zwlr_foreign_toplevel_handle_v1::set_rectangle](https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1#zwlr_foreign_toplevel_handle_v1:request:set_rectangle) to update the minimize position of each view to be within the newly opened subdock
3. Clicking on the icon, CD will send an IPC request to start scale
4. When scale starts, Wayfire will close the xdg-popup
5. The request from step `#2` is processed by Wayfire, triggering the crash seen in the stacktrace above as it now refers to an inert popup's surface
6. CD receives an [xdg_popup::popup_done](https://wayland.app/protocols/xdg-shell#xdg_popup:event:popup_done) event, but it is too late (since it already sent a related request in step `#2`)

Note: likely step `#2` actually happens later, but still before step `#6`. Another possibility is that there is actually a bug in CD and it does send a `set_rectangle` request on an already-closed popup, and I'll look into this separately, but IMO this should lead to a protocol error and not a crash.

### PR DESCRIPTION
**Pull request by dkondor**
Fix originally by @ammen99 https://github.com/WayfireWM/wayfire/issues/2445#issuecomment-2308395997
Fixes #2445 (this just happened to me again :))

### CODE REVIEW

**Comment by soreau** [comment]
Can you say when this happens or how to reproduce? I think I may have hit this when hovering over some link in firefox, but happens very seldomly.

**Comment by dkondor** [comment]
See here for (a bit contrived) example that crashes reliably for me: https://github.com/dkondor/xdg_popup_crasher

So far, I've only been able reproduce this with the help of the foreign-toplevel protocol, but I suspect that it could happen without it as well.

**Comment by soreau** [comment]
> See here for (a bit contrived) example that crashes reliably for me: https://github.com/dkondor/xdg_popup_crasher

Ah, this might be something we could add to the wayfire test suite.
 
> So far, I've only been able reproduce this with the help of the foreign-toplevel protocol, but I suspect that it could happen without it as well.

👍

**Comment by ammen99** [comment]
> Ah, this might be something we could add to the wayfire test suite.

If you have a test client then it would be very cool to add a test, yes! I find crashes especially important :)

**Comment by dkondor** [comment]
> > Ah, this might be something we could add to the wayfire test suite.
> 
> If you have a test client then it would be very cool to add a test, yes! I find crashes especially important :)

Yes, I'm happy to contribute the test! Would you need it to work without user input? (I think it should be doable with little change)

**Comment by ammen99** [comment]
> Yes, I'm happy to contribute the test! Would you need it to work without user input? (I think it should be doable with little change)

You can take a look at the various tests, usually they are run in a nested wayland session and we inject all kinds of input (keyboard, pointer, touch, tablet) so it is fine if it requires a few clicks :)

**Comment by dkondor** [comment]
> > Yes, I'm happy to contribute the test! Would you need it to work without user input? (I think it should be doable with little change)
> 
> You can take a look at the various tests, usually they are run in a nested wayland session and we inject all kinds of input (keyboard, pointer, touch, tablet) so it is fine if it requires a few clicks :)

Created https://github.com/ammen99/wayfire-tests/pull/6 -- actually, it was easier to set up my code to automatically trigger the crash

**Review by ammen99 — APPROVED** [review]
Especially nice when the PR comes with a test as well :)

Thanks!

**Pull request merged**
