### PR TITLE
Remove surface_interface_t

### LINKED ISSUE #1314: Unify input handling
Currently, we have ugly `if (dynamic_cast<...>(...) != null)` checks everywhere in the input code, because it differentiates between compositor surfaces and wlroots surfaces. Instead, the `surface_interface_t` should be extended so that the branching happens there, not in the input code (basically `compositor_surface_t` will be absorbed into `surface_interface_t`)

https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/pointer.cpp#L123
https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/pointer.cpp#L159

and many other places in the touch and tablet inputs as well.

Also pointer constraints:

https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/pointer.cpp#L168

### PR DESCRIPTION
**Pull request by ammen99**
This series of commits completely removes the surface_interface_t class from the codebase. The surface and subsurface functionality has been superseded by the scenegraph and custom nodes.

This PR is the first part of #1309 and also fixes #1314.

### CODE REVIEW

**Comment by ssfdust** [comment]
Hello, I have tested with the PR, it fixes the input-method popup problem.

But when I hover on firefox window in expo mode, the firefox window appears to be jittering. It seems that only it only influences firefox window.


https://user-images.githubusercontent.com/3088610/210216940-546c0310-20c8-429a-b462-fa0c995486fd.mp4

**Comment by ammen99** [comment]
> Hello, I have tested with the PR, it fixes the input-method popup problem.
> 
> But when I hover on firefox window in expo mode, the firefox window appears to be jittering. It seems that it only influences firefox window.
> 
>  jittering-ff.mp4

Do you have blur enabled, and if yes, does disabling it alleviate the problem?

**Comment by ssfdust** [comment]
After disabling blur plugin, the problem disappears.

**Comment by ammen99** [comment]
> Hello, I have tested with the PR, it fixes the input-method popup problem.
> 
> But when I hover on firefox window in expo mode, the firefox window appears to be jittering. It seems that it only influences firefox window.
> 
>  jittering-ff.mp4

I somehow managed to reproduce this once, but cannot reproduce it anymore .. Do you have any idea whether there is any specific action which might cause this bug?

**Comment by ammen99** [comment]
@ssfdust Actually nevermind, I managed to find a way to reproduce reliably. Does http://ix.io/4kgE fix the issue for you as well?

**Comment by ssfdust** [comment]
Yes, the issue was fixed. Thank you very much.

**Comment by ammen99** [comment]
> Yes, the issue was fixed. Thank you very much.

Thanks for testing!

**Pull request merged**
