### PR TITLE
ipc-rules-demo.py: Fix error setting 'workarea'.

### PR DESCRIPTION
**Pull request by flexibeast**

### CODE REVIEW

**Review by ammen99 — COMMENTED** [review]
This seems wrong, we do a query for the output, not for the view. Have you tested this change?

**Comment by flexibeast** [comment]
@ammen99: Yes; the reason i made this change is that the script didn't work for me until i made it.

**Comment by ammen99** [comment]
Ohh I see what is going wrong, this is not the correct fix though. I'll try to fix this and will open a new PR (with the actual fix)

**Comment by flexibeast** [comment]
Ah, fair enough - thanks!

**Pull request closed without merging**
