### PR TITLE
vswipe: add smoothing of scrolling

### PR DESCRIPTION
**Pull request by ammen99**
@myfreeweb I'd appreciate if you can test this and tell me if it makes the experience better or worse. On my setup, I think smoothening the transitions makes it much better, but it'd make sense to gather some more opinions :)

### CODE REVIEW

**Comment by myfreeweb** [comment]
Mostly worse I'd say. Not very bad, but sometimes the latency appears and it feels sort of jelly-like. I absolutely do not like it when I can feel a big movement (whole screen in this case) lagging behind my input.

**Comment by ammen99** [comment]
Okay I'll have to find a way to turn this off then. It probably depends on the hardware - without this, movement feels somehow unstable.

**Comment by ammen99** [comment]
@myfreeweb The new version should make smoothing entirely optional while the user is actually swiping (smoothing happens only after swipe ends). I hope I didn't break anything.

**Comment by myfreeweb** [comment]
btw, here's a GTK patch for scroll interpolation https://gitlab.gnome.org/GNOME/gtk/merge_requests/1117 I haven't tried it yet, but might be worth looking at the interpolation algorithm there

**Pull request merged**
