### PR TITLE
Support scaling only the windows of the focused app

### PR DESCRIPTION
**Pull request by lcolitti**
This adds support to the scale plugin to show only the windows of a given app (or of a given app on all workspaces). This is similar to the compiz feature that scales only the windows of a window group.

### CODE REVIEW

**Comment by ammen99** [comment]
Duplicate of https://github.com/WayfireWM/wayfire/pull/1911

Unfortunately, my stance on this hasn't changed.

Thanks for your PR nonetheless :)

**Comment by ammen99** [comment]
Here is the functionality as a standalone plugin, I think you should easily be able to get this working with an ipc script bound to a hotkey.https://github.com/dkondor/wayfire-scale-ipc

**Comment by lcolitti** [comment]
I get that this is possible to do with an out-of-tree plugin (and thanks for the link), but why require users to do that? The fact that several people have asked for this suggests it's a useful feature. [Mac OS has it](https://support.apple.com/lt-lt/guide/mac-help/mh35798/mac), and compiz does as well (or did before [apparently it broke](https://askubuntu.com/questions/39735/how-do-i-use-initiate-window-picker-for-window-group-in-compiz)). Why not include it? It doesn't seem to be a lot of work to maintain.

FWIW what I am trying to do here is not write code for a specific dock, it's just to improve the user experience of using wayfire and wf-panel. My use case is: I always have dozens of windows open on lots of workspaces, because I use multi-window setups in all apps. I want to pick a window visually from the app I'm already using. Say I'm working on scale.cpp and want to switch to the .hpp file. I know it's another text editor window, but I don't know where it is because its obscured by other windows from other apps (e.g., browsers open at C++ documentation). If I use scale without filters I probably won't be able to pick the window among the dozens of windows I have open - I can see which windows are text editors, but I can't see the one I want because the text in them is too small to read. With this keybinding I can find the window I want.

Sure, it may not be something that most users need. But again - why not support it? Is there a downside?

**Comment by ammen99** [comment]
> Sure, it may not be something that most users need. But again - why not support it? Is there a downside?

The downside is that this repo gets bigger and bigger. I understand the motivation for this particular feature, but this is about the general principle - there are tons of small features which would make sense, but if you put them together, Wayfire's main repo will become too large. This means that basically all features which can be easily delegated to a third-party plugin and I don't deem crucial for the project (or are necessary as a demo of a functionality) are left as an exercise for the reader :)

I myself am using a few external plugins: https://github.com/ammen99/wayfire-plugins

Note that my vision for the project from the very start has been users using multiple plugins from different places. So I don't see this as a downside. I agree that we ought to make installing plugins easier - see #1912.

**Comment by ammen99** [comment]
Also note that, if contributors/Wayfire plugin authors feel like this is a suboptimal way of doing things, nothing prevents people from creating one mega-reposjtory with all kinds of plugins written by various plugins. Think of wayfire-plugins-extra for example :)

**Comment by soreau** [comment]
> This adds support to the scale plugin to show only the windows of a given app (or of a given app on all workspaces). This is similar to the compiz feature that scales only the windows of a window group.

It seems like you can get the same job done with scale title filter plugin, in addition to scale. This way, you can type and match.

**Pull request closed without merging**
