### PR TITLE
Split input.xml into multiple sections

### LINKED ISSUE #824: Divide input.xml into sections
Currently, all the options in [input.xml](https://github.com/WayfireWM/wayfire/blob/master/metadata/input.xml) are grouped together which means all of the options are in the default 'General' tab in wcm. This issue is a call to create subgroups to organize the options in input.xml. The options should be divided into four categories: Keyboard, Mouse, Touch and General. It should be obvious where to place each option; if it does not fit in the first three groups, do not place it in a \<group>, so that it will be placed under the 'General' tab.

The convention is, by default, options are placed under a 'General' tab in wcm. If the xml file contains options in a \<group> section, a new tab is created for those options. The name of the tab is the \<_short> name in the \<group> section. An example of how to do this can be found in [cube.xml](https://github.com/WayfireWM/wayfire/blob/master/metadata/cube.xml#L8-L26).

### PR DESCRIPTION
**Pull request by xbjfk**
Closes #824

### CODE REVIEW

**Review by soreau — CHANGES_REQUESTED** [review]
Looks great in WCM, thanks for this! The only nitpick I have is that I'd like to see the two cursor options under its own 'Cursor' tab rather than leaving it to default to General.

**Review by soreau — APPROVED** [review]
👍

**Comment by soreau** [comment]
Hm, now that I think again, maybe the cursor stuff should go under the mouse tab? What do you think? Either way it's fine with me.

**Comment by xbjfk** [comment]
Maybe, but I think that would confuse touchpad-only users who won't be able to find the cursor options

**Comment by ammen99** [comment]
Seems like this is ready to merge, thanks!

**Pull request merged**
