### PR TITLE
Scale fixes

### PR DESCRIPTION
**Pull request by ammen99**
Yet another round of simplifications, this should not change anything in the behavior.

### CODE REVIEW

**Comment by soreau** [comment]
@dkondor (and anyone else willing) Can you possibly test this and make sure everything still works ok?

**Comment by dkondor** [comment]
Hi,
I've tested quickly and it is working. There are two issues I found:

 - an inactive view creating a child view crashes wayfire (I can reproduce this by having a gedit window with unsaved changes, and middle clicking on it to close it)
 - children of views from a different workspace "fly in" from outside (again, reproduced with the "save changes" dialog of gedit; otherwise child views behave much better)

I'll try to see if I can get a more specific reason for these.

**Comment by dkondor** [comment]
The crash happens in fade_out(), on line 336.

The cause is that when a new child view is added, layout_slots() is called from line 1002, without adding the new view to scale_data. This way, when fade_out() is called, the child view does not have a transformer set up yet.

Maybe fade_in() and fade_out() should check if child views are in scale_data and skip them if not?

**Comment by ammen99** [comment]
> * children of views from a different workspace "fly in" from outside (again, reproduced with the "save changes" dialog of gedit; otherwise child views behave much better)

I think I found the problem, it was a bug in core (#758 is the fix)



> The crash happens in fade_out(), on line 336.
> 
> The cause is that when a new child view is added, layout_slots() is called from line 1002, without adding the new view to scale_data. This way, when fade_out() is called, the child view does not have a transformer set up yet.
> 
> Maybe fade_in() and fade_out() should check if child views are in scale_data and skip them if not?

Hmm, I think I removed a lot of similar checks but I see they will be needed here.

**Comment by ammen99** [comment]
The last commit should fix the crashing issue, please take a look again @dkondor when you get the time.

**Comment by dkondor** [comment]
Hi,
I've tested and both the crash and dialog placement is fixed (merging with the other branch).
I've seen another issue with dialogs; I've commented on #582 with it.

**Comment by ammen99** [comment]
I found a crash myself, when minimizing views in interactive mode. Will have to investigate further.

**Comment by ammen99** [comment]
@dkondor I would appreciate one more test since I found a lot more "simplifications", if you have time & motivation of course :)
Also thanks for the testing so far!

**Comment by dkondor** [comment]
Hi,
I'm seeing three issues so far.

The first one is that when starting scale, sometimes all views are transparent (faded out), see the attached screenshot. Interestingly, this only happens the first time scale is run. If I select a view to exit scale, and then restart scale, the active view is now opaque (faded in) as expected.
scale1

**Comment by dkondor** [comment]
The second one is a crash that happens sometimes when deactivating scale. Unfortunately, I cannot reliably reproduce it. So far, I've only seen it when deactivating scale with the toggle keybinding, and only in the case of the previous issue (all views are faded out), but not always.

One stacktrace:

```
EE 28-09-20 11:46:13.625 - [src/main.cpp:244] Fatal error: Segmentation fault
EE 28-09-20 11:46:13.787 - #1  signal_handler(int) ../src/main.cpp:245
EE 28-09-20 11:46:13.979 - #2  killpg ??:?
EE 28-09-20 11:46:14.027 - #3  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<wf::custom_data_t, std::default_delete<wf::custom_data_t> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<wf::custom_data_t, std::default_delete<wf::custom_data_t> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/hashtable.h:638
EE 28-09-20 11:46:14.074 - #4  std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<wf::custom_data_t, std::default_delete<wf::custom_data_t> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<wf::custom_data_t, std::default_delete<wf::custom_data_t> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/hashtable_policy.h:706
EE 28-09-20 11:46:14.122 - #5  std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<wf::custom_data_t, std::default_delete<wf::custom_data_t> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<wf::custom_data_t, std::default_delete<wf::custom_data_t> > > > >::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unordered_map.h:974
EE 28-09-20 11:46:14.170 - #6  wf::object_base_t::has_data(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../src/core/object.cpp:170
EE 28-09-20 11:46:14.243 - #7  bool wf::object_base_t::has_data<wf::layer_view_data_t>() ../src/api/wayfire/object.hpp:165
EE 28-09-20 11:46:14.317 - #8  wf::output_layer_manager_t::get_view_layer(nonstd::observer_ptr<wf::view_interface_t>) ../src/output/workspace-impl.cpp:157
EE 28-09-20 11:46:14.390 - #9  wf::workspace_manager::get_view_layer(nonstd::observer_ptr<wf::view_interface_t>) ../src/output/workspace-impl.cpp:1157
EE 28-09-20 11:46:14.446 - #10 wf::output_impl_t::focus_view(nonstd::observer_ptr<wf::view_interface_t>, unsigned int) ../src/output/output.cpp:244
EE 28-09-20 11:46:14.502 - #11 wf::output_impl_t::focus_view(nonstd::observer_ptr<wf::view_interface_t>, bool) ../src/output/output.cpp:303
EE 28-09-20 11:46:14.539 - #12 wayfire_scale::refocus() ../plugins/single_plugins/scale.cpp:1065
EE 28-09-20 11:46:14.576 - #13 wayfire_scale::deactivate() ../plugins/single_plugins/scale.cpp:1216
EE 28-09-20 11:46:14.613 - #14 wayfire_scale::handle_toggle(bool) ../plugins/single_plugins/scale.cpp:207
EE 28-09-20 11:46:14.649 - #15 wayfire_scale::toggle_cb::{lambda(wf::activator_source_t, unsigned int)#1}::operator()(wf, unsigned int) const ../plugins/single_plugins/scale.cpp:225
EE 28-09-20 11:46:14.685 - #16 std::_Function_handler<bool (wf::activator_source_t, unsigned int), wayfire_scale::toggle_cb::{lambda(wf::activator_source_t, unsigned int)#1}>::_M_invoke(std::_Any_data const&, wf::activator_source_t&&, unsigned int&&) ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:282
EE 28-09-20 11:46:14.750 - #17 std::function<bool (wf::activator_source_t, unsigned int)>::operator()(wf::activator_source_t, unsigned int) const ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:687
EE 28-09-20 11:46:14.799 - #18 operator() ../src/core/seat/keyboard.cpp:311
EE 28-09-20 11:46:14.846 - #19 std::_Function_handler<bool (), input_manager::match_keys(unsigned int, unsigned int, unsigned int)::$_10>::_M_invoke(std::_Any_data const&) ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:282
EE 28-09-20 11:46:14.910 - #20 std::function<bool ()>::operator()() const ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:687
EE 28-09-20 11:46:14.958 - #21 input_manager::handle_keyboard_key(unsigned int, unsigned int) ../src/core/seat/keyboard.cpp:424
EE 28-09-20 11:46:15.006 - #22 operator() ../src/core/seat/keyboard.cpp:31
EE 28-09-20 11:46:15.054 - #23 std::_Function_handler<void (void*), wf_keyboard::setup_listeners()::$_0>::_M_invoke(std::_Any_data const&, void*&&) ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:299
EE 28-09-20 11:46:15.077 - #24 std::function<void (void*)>::operator()(void*) const ../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:687
EE 28-09-20 11:46:15.101 - #25 wf::wl_listener_wrapper::emit(void*) ../src/util.cpp:518
EE 28-09-20 11:46:15.124 - #26 handle_wrapped_listener(wl_listener*, void*) ../src/util.cpp:454
EE 28-09-20 11:46:15.249 - #27 wlr_signal_emit_safe ../util/signal.c:22
EE 28-09-20 11:46:15.279 - #28 wlr_keyboard_notify_key ../types/wlr_keyboard.c:95
EE 28-09-20 11:46:15.294 - #29 send_key_event ../backend/x11/input_device.c:29
EE 28-09-20 11:46:15.306 - #30 handle_x11_xinput_event ../backend/x11/input_device.c:127
EE 28-09-20 11:46:15.320 - #31 handle_x11_event ../backend/x11/backend.c:81
EE 28-09-20 11:46:15.332 - #32 x11_event ../backend/x11/backend.c:94
EE 28-09-20 11:46:15.342 - #33 wl_event_loop_dispatch /home/dkondor/program/wayland/src/event-loop.c:1027
EE 28-09-20 11:46:15.351 - #34 wl_display_run /home/dkondor/program/wayland/src/wayland-server.c:1349
EE 28-09-20 11:46:15.381 - #35 main ../src/main.cpp:406
EE 28-09-20 11:46:15.516 - #36 __libc_start_main ../csu/libc-start.c:344
EE 28-09-20 11:46:15.555 - #37 ?? ??:0
```

**Comment by dkondor** [comment]
The third one is that when a child view is closed, it is temporarily rearranged as if it was a toplevel view. So all the views start moving, and then (after the child disappeared), all of them move back to their original locations. So far I was not able to make a screenshot of this, so let me know if you need more info.

This is something that came up before and I think it was fixed by commit 4bbdbad9c9fc02bff430cbf5c0217413dc9411c5 by @soreau -- I think the main cause was that the "view-layer-attached" signal is emitted when closing the child view.

**Comment by soreau** [comment]
> Hi,
> I'm seeing three issues so far.
> 

To be clear, none of these issues exist on the current `scale` branch?

> The second one is a crash that happens sometimes when deactivating scale. Unfortunately, I cannot reliably reproduce it. So far, I've only seen it when deactivating scale with the toggle keybinding, and only in the case of the previous issue (all views are faded out), but not always.

Could it be that it only happens while a close animation is in progress for one of the views?

**Comment by dkondor** [comment]
> > Hi,
> > I'm seeing three issues so far.
> 
> To be clear, none of these issues exist on the current `scale` branch?

Good question. I've tried, but do not see any of these issues there.

> 
> > The second one is a crash that happens sometimes when deactivating scale. Unfortunately, I cannot reliably reproduce it. So far, I've only seen it when deactivating scale with the toggle keybinding, and only in the case of the previous issue (all views are faded out), but not always.
> 
> Could it be that it only happens while a close animation is in progress for one of the views?

No, as far as I can tell. Views were open normally, there was no close event / animation, I just pressed the toggle binding.

**Comment by ammen99** [comment]
@dkondor Thanks for the test.

- Problem 1 should be fixed with https://github.com/WayfireWM/wayfire/pull/757/commits/febef4c8bcc336fca48f2a9a0c689fe76d4fd47f
- I could not reproduce problem 2, but current_focus_view is not initialized in activate() so in refocus() it might be used with uninitialized values. I fixed that, and I hope https://github.com/WayfireWM/wayfire/pull/757/commits/58da214c2beb47d00a6d4e11b6146b29846d5dee removes the crash you get.
- Problem 3 is actually a problem in core, will be fixed by #755. I suppose that it works on the scale branch because @soreau has put a workaround (which I deleted)

**Comment by dkondor** [comment]
I've tried again and problems 1 and 2 seem to be fixed. Problem 3 is also fixed by merging the branch from #755.

I've noticed a new problem: if no views are focused initially, keyboard interaction with scale (ESC, ENTER, arrows) do not work. This happens e.g. when starting scale from all workspaces from a workspace without any views.

What I think happens is that process_key() always returns in line 522, since current_focus_view is not set. What I expect is that ESC should always work, even if there is no selected view. Also i think it is better in this case if arrows work by selecting an arbitrary view.

Another approach could be to always focus and arbitrary view if no view is focused when starting scale. Even in this case, ESC could be used to cancel if we remember that initial_focus_view was null.

**Comment by ammen99** [comment]
@dkondor I made it so that a view is always selected, but ESC still returns to the empty workspace if it was empty initially.

**Pull request merged**
