### PR TITLE
bump wf-config and wlroots

### LINKED ISSUE #690: Gentoo: Master fails to build with system wlroots & wfconfig here...
Installed versions:  9999*l(14:11:45 06/08/2020)(elogind gles system-wfconfig system-wlroots -systemd)

Master configured to build with system wlroots and wfconfig already installed now fails to build here.

[gui-wm:wayfire-9999:20200815-105133.log.zip](https://github.com/WayfireWM/wayfire/files/5078522/gui-wm.wayfire-9999.20200815-105133.log.zip)

Thls 4 ur attention, interest & support.

### PR DESCRIPTION
**Pull request by ammen99**
Fixes #690 

@epsilon-0 Does this look ok?

### CODE REVIEW

**Comment by epsilon-0** [comment]
Yes, it is correct.
The has wlroots#379835c42f182aa2c8fa814dea20a325361f8bdf is on the master branch so this works perfectly!

Thanks.

**Comment by epsilon-0** [comment]
building and reporting in 1 min

**Comment by epsilon-0** [comment]
OK, it worked :smile_cat:

**Comment by ammen99** [comment]
Good, thanks for the report!

**Pull request merged**
