### PR TITLE
blur optimizations

### LINKED ISSUE #669: [blur] unnecessary blurring - performance
So I disabled blur and was shocked how much faster everything became.
The only view with transparent background is wf-panel

What I noticed though is that the GTK applications have their window shadow blurred,
which is part of the wm_geometry but not of the view geometry AFAIK.

I don't think that the window shadow should be eligible for blur.

### PR DESCRIPTION
**Pull request by ammen99**
- blur: add option to configure which views should be blurred
- blur: calculate blur region

The new option is called `blur/blur_by_default` and has type criteria. If you want a bit more efficient blur, set only views that you want to blur.

I believe we can close #669 with this PR.

### CODE REVIEW

**Comment by myfreeweb** [comment]
Looks like this introduces crashes (asserts in the driver)

```
    frame #3: 0x000000080c40d501 libc.so.7`__assert(func=<unavailable>, file=<unavailable>, line=<unavailable>, failedexpr=<unavailable>) at assert.c:51:2
    frame #4: 0x00000008344e0e7e radeonsi_dri.so`clip_right_or_top(srcX0=<unavailable>, srcX1=<unavailable>, dstX0=<unavailable>, dstX1=<unavailable>, maxValue=<unavailable>) at image.c:813:7
    frame #5: 0x00000008344e0a8a radeonsi_dri.so`_mesa_clip_blit(ctx=0x0000000841bfeac0, readFb=0x000000085e171a00, drawFb=0x00000008603ca400, srcX0=<unavailable>, srcY0=0x00007fffffffc5a4, srcX1=0x00007fffffffc5a8, srcY1=0x00007fffffffc5ac, dstX0=0x00007fffffffc5b0, dstY0=0x00007fffffffc5b4, dstX1=0x00007fffffffc5b8, dstY1=0x00007fffffffc5bc) at image.c:946:4
    frame #6: 0x00000008343078a0 radeonsi_dri.so`st_BlitFramebuffer(ctx=0x0000000841bfeac0, readFB=0x000000085e171a00, drawFB=0x00000008603ca400, srcX0=<unavailable>, srcY0=<unavailable>, srcX1=3452, srcY1=2194, dstX0=392, dstY0=-34, dstX1=3452, dstY1=6, mask=16384, filter=9729) at st_cb_blit.c:89:9
    frame #7: 0x0000000834396a21 radeonsi_dri.so`_mesa_BlitFramebuffer [inlined] blit_framebuffer(ctx=0x0000000841bfeac0, readFb=0x000000085e171a00, drawFb=0x00000008603ca400, srcX0=392, srcY0=2154, srcX1=3452, srcY1=2194, dstX0=392, dstY0=-34, dstX1=3452, dstY1=6, mask=16384, filter=9729, no_error=false, func=<unavailable>) at blit.c:576:4
    frame #8: 0x00000008343964e4 radeonsi_dri.so`_mesa_BlitFramebuffer [inlined] blit_framebuffer_err(ctx=0x0000000841bfeac0, readFb=0x000000085e171a00, drawFb=0x00000008603ca400, srcX0=392, srcY0=2154, srcX1=3452, srcY1=2194, dstX0=392, dstY0=-34, dstX1=3452, dstY1=6, mask=<unavailable>, filter=9729, func=<unavailable>) at blit.c:594
    frame #9: 0x00000008343964e4 radeonsi_dri.so`_mesa_BlitFramebuffer(srcX0=392, srcY0=2154, srcX1=3452, srcY1=2194, dstX0=<unavailable>, dstY0=-34, dstX1=3452, dstY1=6, mask=16384, filter=9729) at blit.c:635
    frame #10: 0x000000086f84ab2b libblur.so`wf_blur_transformer::~wf_blur_transformer() [inlined] std::__1::__function::__value_func<nonstd::observer_ptr<wf_blur_base> ()>::~__value_func(this=0x00000008603c3ca0) at functional:1842:20
    frame #11: 0x000000086f84ab27 libblur.so`wf_blur_transformer::~wf_blur_transformer() [inlined] std::__1::function<nonstd::observer_ptr<wf_blur_base> ()>::~function(this=0x00000008603c3ca0) at functional:2543
    frame #12: 0x000000086f84ab27 libblur.so`wf_blur_transformer::~wf_blur_transformer() [inlined] wf_blur_transformer::~wf_blur_transformer(this=0x00000008603c3c90) at blur.cpp:12
    frame #13: 0x000000086f84ab19 libblur.so`wf_blur_transformer::~wf_blur_transformer(this=0x00000008603c3c90) at blur.cpp:12
    frame #14: 0x00000000002d94c6 wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator()(std::__1::function<void (wf::signal_data_t*)>*&) [inlined] std::__1::__function::__value_func<void (wf::signal_data_t*)>::operator(this=<unavailable>, __args=0x00007fffffffc7c8)(wf::signal_data_t*&&) const at functional:1884:16
    frame #15: 0x00000000002d94b3 wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator()(std::__1::function<void (wf::signal_data_t*)>*&) [inlined] std::__1::function<void (wf::signal_data_t*)>::operator(this=<unavailable>, __arg=0x00007fffffffc9a0)(wf::signal_data_t*) const at functional:2556
    frame #16: 0x00000000002d94b3 wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator()(std::__1::function<void (wf::signal_data_t*)>*&) [inlined] auto wf::signal_provider_t::emit_signal(this=<unavailable>, call=<unavailable>)::$_3::operator()<std::__1::function<void (wf::signal_data_t*)>*>(std::__1::function<void (wf::signal_data_t*)>*) const at object.cpp:136
    frame #17: 0x00000000002d94ab wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator()(std::__1::function<void (wf::signal_data_t*)>*&) [inlined] decltype(__f=<unavailable>, __args=<unavailable>)::$_3&>(fp)(std::__1::forward<std::__1::function<void (wf::signal_data_t*)>*&>(fp0))) std::__1::__invoke<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3&, std::__1::function<void (wf::signal_data_t*)>*&>(wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3&, std::__1::function<void (wf::signal_data_t*)>*&) at type_traits:3899
    frame #18: 0x00000000002d94a8 wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator()(std::__1::function<void (wf::signal_data_t*)>*&) [inlined] void std::__1::__invoke_void_return_wrapper<void>::__call<wf::signal_provider_t::emit_signal(__args=<unavailable>, __args=<unavailable>)::$_3&, std::__1::function<void (wf::signal_data_t*)>*&>(wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3&, std::__1::function<void (wf::signal_data_t*)>*&) at __functional_base:348
    frame #19: 0x00000000002d94a8 wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator()(std::__1::function<void (wf::signal_data_t*)>*&) [inlined] std::__1::__function::__alloc_func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator(this=<unavailable>, __arg=<unavailable>)(std::__1::function<void (wf::signal_data_t*)>*&) at functional:1557
    frame #20: 0x00000000002d94a8 wayfire`std::__1::__function::__func<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3, std::__1::allocator<wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*)::$_3>, void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator(this=<unavailable>, __arg=<unavailable>)(std::__1::function<void (wf::signal_data_t*)>*&) at functional:1731
    frame #21: 0x00000000002d8ab9 wayfire`wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*) [inlined] std::__1::__function::__value_func<void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator(this=0x00007fffffffc810, __args=<unavailable>)(std::__1::function<void (wf::signal_data_t*)>*&) const at functional:1884:16
    frame #22: 0x00000000002d8aaa wayfire`wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*) [inlined] std::__1::function<void (std::__1::function<void (wf::signal_data_t*)>*&)>::operator(this=0x00007fffffffc810, __arg=<unavailable>)(std::__1::function<void (wf::signal_data_t*)>*&) const at functional:2556
    frame #23: 0x00000000002d8aaa wayfire`wf::signal_provider_t::emit_signal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, wf::signal_data_t*) at safe-list.hpp:203
    frame #24: 0x00000000002d8a79 wayfire`wf::signal_provider_t::emit_signal(this=<unavailable>, name="", data=0x00007fffffffc9a0) at object.cpp:134
    frame #25: 0x000000000032858a wayfire`wf::render_manager::impl::workspace_stream_update(this=0x000000086034e000, stream=0x00000008601c43c0, scale_x=<unavailable>, scale_y=<unavailable>) at render-manager.cpp:1143:29
    frame #26: 0x000000000032aa9e wayfire`wf::render_manager::impl::default_renderer(this=0x000000086034e000) at render-manager.cpp:666:13
    frame #27: 0x000000000032a2b7 wayfire`wf::render_manager::impl::render_output(this=<unavailable>) at render-manager.cpp:695:13
    frame #28: 0x000000000032998d wayfire`wf::render_manager::impl::paint(this=0x000000086034e000) at render-manager.cpp:751:9
```

**Comment by myfreeweb** [comment]
Also, funny how the default `type is "toplevel"` seemed to match grid's snap rectangles

**Comment by ammen99** [comment]
> Looks like this introduces crashes (asserts in the driver)

I had forgotten to clip damage, should be fixed now.

> Also, funny how the default `type is "toplevel"` seemed to match grid's snap rectangles

Funny indeed ;)

**Comment by ammen99** [comment]
The crash from @myfreeweb should be fixed now. I also managed to find another optimization and to make the degrade option much more stable, which should also make it even faster if you want a lot of blur. My settings:

```ini
[blur]
method = kawase
kawase_degrade = 8
kawase_iterations = 2
kawase_offset = 2.0
```

This makes Wayfire's rendering consume only 3x more GPU power than without blur :)

@soreau Has found a few artifacts in some special cases, so this will be merged once I manage to reproduce them and fix (however it happens only with iterations=0,1 so that should not really be an issue)

**Pull request merged**
