### PR TITLE
Error no longer wrongly logged for move and resize window rules

### PR DESCRIPTION
**Pull request by JordanL2**
Before this change, all move and resize window rules would wrongly log this error:

"View action interface: Unsupported action execution requested. Name: "

### CODE REVIEW

**Comment by JordanL2** [comment]
I'm sure not how to see what was wrong with the code style.

**Comment by JordanL2** [comment]
By the way I tried squashing my two commits into one and somehow ended up with seven commits.. If you want this PR can be deleted and I'll make another one.

**Comment by soreau** [comment]
> By the way I tried squashing my two commits into one and somehow ended up with six commits.. If you want this PR can be deleted and I'll make another one.

You can force-push your branch so you don't have to make another PR.

**Comment by JordanL2** [comment]
> You can force-push your branch so you don't have to make another PR.

I got it into a pretty bad state so made another one: https://github.com/WayfireWM/wayfire/pull/906

I'll try and figure out how to properly squash commits before trying it again!

**Pull request closed without merging**
