### PR TITLE
Fast switcher uses focus order instead of stack order

### LINKED ISSUE #569: Add an option for window switcher to cycle back and forth
A suggestion to optionally make it work like common Linux desktops and Windows. Single activation alt + tab goes back and forth between same two windows. To switch to the next you need to press tab again while alt is still pressed.

>On Windows 10, when you use the "Alt + Tab" keyboard shortcut, you'll open the task switcher, which is an experience that allows you to view and switch back and forth between the two most recent applications or any other running task, by pressing and holding the "Alt" key and using the "Tab" key to cycle through.

If possible it should skip animation and preview if key is released quickly to not flicker the screen.

### PR DESCRIPTION
**Pull request by pushqrdx**
this should fix #569 and makes Fast Switcher plugin more intuitive to use

### CODE REVIEW

**Comment by ammen99** [comment]
That seems more like a quick workaround than a real fix. You should sort views by their last focused timestamp, and that will give you the result you want for free ;)

**Comment by ammen99** [comment]
Not to mention that previous_view_index could either disappear, a plugin might reorder views, or something else.

**Comment by ammen99** [comment]
I looked through the code and I think it might require a bit more work. The function `update_views` refreshes the list of views, you should sort the views there according to last focused timestamp.

Also, you should make sure that fast-switcher **doesn't** call `focus_view` except when it is exiting, otherwise, this would change the last focus order.

**Comment by pushqrdx** [comment]
@ammen99 what about this, i didn't change any code that calls `focus_view` and it seems to work, the order doesn't get messed up and it toggles correctly

**Comment by pushqrdx** [comment]
@ammen99 I have been using it for a while now, the latest edits i pushed sort views according to their time stamp which does exactly what's expected, should fix #852

**Comment by ammen99** [comment]
LGTM. Can you however extend the function update_views instead of removing it?

**Review by ammen99 — APPROVED** [review]
Thanks!

**Pull request merged**
