### PR TITLE
zero copy expo

### PR DESCRIPTION
**Pull request by ammen99**
This implements workspace-wall on top of scenegraph.

TODO:

- [x] Figure out how to send frame done events to surfaces with scenegraph

### CODE REVIEW

**Comment by ammen99** [comment]
@szbergeron You might be interested in trying this out :)

**Comment by ssfdust** [comment]
Hello, when will this PR be merged ? It fixes #1660 which is very important for me.

**Comment by ssfdust** [comment]
After testing with this PR, when I active the expo plugin with super+e, my desktop is keep flashing...

https://user-images.githubusercontent.com/3088610/209644030-89493a2c-f74f-41e7-bfd4-96f790144584.mp4

**Comment by ssfdust** [comment]
The patch also makes the input-method popups to be wired in all xwayland windows.

https://user-images.githubusercontent.com/3088610/210025817-dcf8c6fb-2672-4f3f-b7c8-d5fa0f6cc60b.mp4

**Comment by ammen99** [comment]
> The patch also makes the input-method popups to be wired in all xwayland windows.
> 

I'm not sure what you mean by wired, is that a good or a bad thing?

**Comment by ssfdust** [comment]
Sorry by typo, I mean weird.

> > The patch also makes the input-method popups to be wired in all xwayland windows.
> 
> I'm not sure what you mean by wired, is that a good or a bad thing?

**Comment by ammen99** [comment]
@ssfdust @soreau Thank you for testing this. I just pushed a few commits which will hopefully fix the visual glitches introduced by the PR. As for the popups/etc. which don't show up properly, a proper fix is included in #1669 (which is in fact also ready for testing).

**Comment by ammen99** [comment]
Actually I just found a way to reproduce more artifacts (even though some were definitely fixed) will have to look into that in more detail.

**Comment by ssfdust** [comment]
Happy new year, I have updated to the latest commit on my another desktop, everything seems ok now.

**Comment by ammen99** [comment]
Remaining issues should be fixed now. I also tested this in a 4K setup, the old expo struggles with just 1 fullscreen glxgears, the new expo is always butter smooth :)

**Comment by ssfdust** [comment]
I tested with the latest commit, it dose work much better. When will the PR be merged?

**Comment by ammen99** [comment]
> I tested with the latest commit, it dose work much better. When will the PR be merged?

Thanks for testing. I think this PR is now ready for merge, #1669 will come soon as well (it is ready for testing, too).

**Pull request merged**
