### PR TITLE
use OpenMP for simplifying thread setup in fire particle animations (master branch)

### PR DESCRIPTION
**Pull request by epsilon-0**
**Notice: Wayfire's development is temporarily happening in the `stabilize-api` branch. If you open a pull request for the master branch, it will likely not be merged before the stabilize-api branch is itself merged into master.**

### CODE REVIEW

**Comment by ammen99** [comment]
LGTM, can you rebase on top of master to get the CI working, too?

**Comment by epsilon-0** [comment]
updated.

**Review by ammen99 — CHANGES_REQUESTED** [review]
Note: the CI still doesn't pass.

**Comment by ammen99** [comment]
Ping

**Comment by epsilon-0** [comment]
Fixed!

**Review by ammen99 — APPROVED** [review]
LGTM, thanks!

I will merge after the 0.8.1 release to avoid adding new dependencies for a minor release.

**Review by ammen99 — APPROVED** [review]

**Pull request merged**
