### PR TITLE
fix build broken by wlroots commit 59fa3637c348

### PR DESCRIPTION
**Pull request by pelikan**

### CODE REVIEW

**Comment by ammen99** [comment]
The wlroots submodule likely also needs a bump, otherwise lgtm.

**Comment by pelikan** [comment]
I hope I've done this correctly (first time using submodules).

**Comment by MrSwedish** [comment]
thaaanks, this would make me able to build wayfire again
(haven't tested, but the error said something about clientpending)

**Review by ammen99 — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
