### PR TITLE
hotspot support

### LINKED ISSUE #298: add hotcorner support
add hot corner support same as kwin.
where we can let cursor touch the corner and a command gets activated 
for eg.
window overview.desktop grid.show desktop.desktop cube.
etc
at top left corner. and other corners.

### PR DESCRIPTION
**Pull request by ammen99**
This PR adds basic support for hotspots. The required changes for wf-config are not merged yet,
see https://github.com/WayfireWM/wf-config/tree/add-hotspots.

Hotspots are currently supported as part of activator bindings. For example,

```ini
[expo]
toggle = hotspot top-left 100x10 1000
```

The meaning of the example: the hotspot is in the top-left corner.
It spawns an area of 100 pixels along both edges, with a "width" of 10 pixels, i.e. the same as explained
here: https://github.com/WayfireWM/wayfire/issues/572

The last parameter means that the cursor needs to stay for `1000` milliseconds in the hotspot to activate it.

Fixes #298

### CODE REVIEW

**Comment by damianatorrpm** [comment]
I'm building now with this as well to test, after thinking about it,
it would make more sense to not do special handling here,
but instead for example scale (the only plugin I care w/hotspots for)
to have an option to deny these request if the activator source is hotspot.

**Comment by damianatorrpm** [comment]
works fine with the exception that changing options to an hotspot requires wayfire restart
at runtime changing
```
[scale]
toggle = <super> | hotspot top-left 10x100 100
```

to 

```
[scale]
toggle = <super> | hotspot bottom-left 10x100 100
```
has no effect

**Comment by ammen99** [comment]
> works fine with the exception that changing options to a hotspot requires wayfire restart
> at runtime changing

Ah yes I forgot to recreate hotspots on config reload, I'll fix it.

**Comment by damianatorrpm** [comment]
hotspot reload still doesn't work 
```
[scale]
toggle = <super> | hotspot top-left 10x100 100
```
to

```
[scale]
toggle = <super> | hotspot bottom-left 10x100 100
```
I used branch hotspot-support for build or do other things need to applied (except wf-config)

**Comment by ammen99** [comment]
@damianatorrpm I think I fixed the reloading issue, can you try again? (also update wf-config because the bug was there, the fix was pushed on the same branch)

**Comment by damianatorrpm** [comment]
@ammen99 Yep, work fine

**Pull request merged**
