### PR TITLE
grid: unset fullscreen for restore

### LINKED ISSUE #929: [grid] restore should reset decoration
**Describe the bug**
When restoring a full-screened view, the decorations are not reset.

**To Reproduce**
1. Enable grid and wm-actions plugins
2. Full screen view with wm-actions plugin
3. Restore view with grid plugin

**Expected behavior**
The decoration is reset when a full-screened view is no longer full screen.

**Wayfire version**
0.6.0

### PR DESCRIPTION
**Pull request by travankor**
fixes #929 

todo: need to find a way to set fullscreen for restore

### CODE REVIEW

**Comment by soreau** [comment]
> todo: need to find a way to set fullscreen for restore

I'm not really sure this makes sense. If you un-fullscreen a view with this binding, then maximize it, then use the binding again, what are you expecting to happen?

**Comment by travankor** [comment]
well, this might not be needed, but:

1) fullscreen view
2) move view
3) restore view

should thr last restore should re-fullscreen the view?

**Comment by damianatorrpm** [comment]
In general that's what wayfire does. But 'grid' plugin doesn't to move operations, instead it does tile operation.
(I don't use grid so I'm not sure about it's details)

**Comment by ammen99** [comment]
> 3\. 
> 
> should the last restore re-fullscreen the view?

I don't think so

**Review by ammen99 — APPROVED** [review]
Thanks!

**Pull request merged**
