### PR TITLE
Add packaging status

### PR DESCRIPTION
**Pull request by tim77**
Please add packaging status. Wayfire with all required components [packaged for Fedora](https://src.fedoraproject.org/rpms/wayfire) (for Rawhide at this moment). Waiting for your new 0.3 version. :)

### CODE REVIEW

**Comment by ammen99** [comment]
Would this also pull wf-shell as well? (`dnf install wayfire`) or just Wayfire itself?

**Comment by tim77** [comment]
Yes, `wf-shell` and `wayfire-config-manager` as weak depencies.

**Comment by soreau** [comment]
> Yes, `wf-shell` and `wayfire-config-manager` as weak depencies.

:+1:

**Comment by ammen99** [comment]
I figure we can merge this even without having a release.
Thanks!

**Pull request merged**
