### PR TITLE
Scale fixes

### PR DESCRIPTION
**Pull request by ammen99**
A few simplifications I noticed, see individual commits for explanations

### CODE REVIEW

**Comment by soreau** [comment]
This seems to break more things than it fixes. Reportedly, if you scale, close a view and unscale while the close animation is running, it will crash wayfire. Can you rebase and also check if this is the case?

**Comment by ammen99** [comment]
> This seems to break more things than it fixes. Reportedly, if you scale, close a view and unscale while the close animation is running, it will crash wayfire. Can you rebase and also check if this is the case?

I can't repro with these steps.

**Comment by kode54** [comment]
Can no longer reproduce the issue I was having.

**Comment by soreau** [comment]
@dkondor Can you please test this PR?

**Comment by dkondor** [comment]
It seems to be working, I don't see the previous issues after some quick testing.
Two small issues I noticed (both with the case of scale with all workspaces):
 - exiting interactive scale (or non-interactive scale with the activator keybinding) does not switch to the workspace of the selected view (although this is what I'd expect)
 - starting non-interactive scale from an empty workspace and then exiting with the "cancel" key (ESC), it still switches to the view that was first highlighted; I'd expect to stay on the original, empty workspace in this case
I don't remember if these were present before, probably yes, but I didn't notice or care about them.

It still has the issue of child views from other workspaces appearing in "wrong" locations (instead of coming from their workspace, they appear in their location in the current workspace), but I think this is caused by issue #582 and is not a problem with scale itself.

Also, menus (and other popups) appear unscaled. For interactive mode, I think this is OK since it makes it easier to interact with them; for non-interactive scale, my expectation would be for popups to close or at least be scaled when starting scale.

**Comment by soreau** [comment]
> It seems to be working, I don't see the previous issues after some quick testing.

Great, thanks for testing.

> Two small issues I noticed (both with the case of scale with all workspaces):
> 
>     * exiting interactive scale (or non-interactive scale with the activator keybinding) does not switch to the workspace of the selected view (although this is what I'd expect)
 
I don't really want to bomb this PR with unrelated conversation but since scale isn't merged yet, I'm not sure an issue would be appropriate, so I think here is fine.
My question is, how are you exiting interactive scale if not with the activator? In any event, I imagine it shouldn't be too hard to fix this.

>     * starting non-interactive scale from an empty workspace and then exiting with the "cancel" key (ESC), it still switches to the view that was first highlighted; I'd expect to stay on the original, empty workspace in this case

Probably yet another bug, hopefully shouldn't be too difficult to find a solution.

> I don't remember if these were present before, probably yes, but I didn't notice or care about them.
> 
> It still has the issue of child views from other workspaces appearing in "wrong" locations (instead of coming from their workspace, they appear in their location in the current workspace), but I think this is caused by issue #582 and is not a problem with scale itself.

Yes, I think this is a vswitch bug. I don't think it handles child views.
> Also, menus (and other popups) appear unscaled. For interactive mode, I think this is OK since it makes it easier to interact with them; for non-interactive scale, my expectation would be for popups to close or at least be scaled when starting scale.

**Comment by soreau** [comment]
@dkondor [This](http://ix.io/2vYF) fixes the bugs you describe, but might introduce others, I haven't tested thoroughly. Can you try it and see if you notice any other problems?

**Comment by dkondor** [comment]
Hi,
I had limited time to test. So far, it seems it fixes the errors, but I think it introduces a separate issues:
 - Now if I start from an empty workspace, and exit with the activator toggle, it never switches workspaces (either interactive or non-interactive). It does switch workspaces in non-interactive mode if I click with the mouse. What I'd expect to happen is that it switches to a new workspace in all cases, except when I cancel it (i.e. non-interactive mode and press ESC). Alternatively, I could imagine it only switching if I explicitly selected a view.
 - In some cases, it switches to a bad workspace. I haven't found a clear pattern, but two examples that seem to always happen, assuming a 3x3 grid of workspaces and a view on the top left (0,0) and middle (1,1) one:
    1. Starting scale from the middle and selecting the view on the top left: the screen goes blank for a few seconds, and I see the following message in the terminal: "EE 03-09-20 12:14:17.322 - [src/output/workspace-impl.cpp:612] Attempt to set invalid workspace: (-1,-1) workspace grid size is 3x3" After this, it correctly switches to the top left (0,0) workspace. This only happens when selecting the view by clicking or pressing ENTER in non-interactive mode. Using the activator toggle works well.
    2. Starting from the empty bottom left (2,0) workspace, and selecting the view in the middle (1,1), it actually ends up on the top middle (0,1) workspace

**Comment by dkondor** [comment]
> My question is, how are you exiting interactive scale if not with the activator? In any event, I imagine it shouldn't be too hard to fix this.

In non-interactive mode, either ENTER (should switch to the selected view), ESC (to cancel), or clicking on a view (should switch to that view)

**Comment by soreau** [comment]
@dkondor Does [this](http://ix.io/2vYF) work any better?

**Comment by dkondor** [comment]
Hi,
yes, but I see two issues:
 - now if I exit with ESC, it does not refocus the initial view (it keeps focusing the last selected); I've tried looking into this, but i have not idea what is happening
 - if I exit with ENTER, switching workspaces does not work properly; I think this is issue #676 , I will reopen and comment there

**Comment by soreau** [comment]
> Hi,
> yes, but I see two issues:
> 
>     * now if I exit with ESC, it does not refocus the initial view (it keeps focusing the last selected); I've tried looking into this, but i have not idea what is happening

Refresh the patch link and try again. I think I was missing one line to fix the ESC not refocusing initial view.

> 
>     * if I exit with ENTER, switching workspaces does not work properly; I think this is issue #676 , I will reopen and comment there

I noticed this as well. I debugged this and it is indeed the reason why we're seeing black screen sometimes. Funny enough, vswitch has [this comment](https://github.com/WayfireWM/wayfire/blob/master/plugins/single_plugins/vswitch.cpp#L161) before supposedly clamping away any way for this exact case to happen.

**Comment by dkondor** [comment]
> Refresh the patch link and try again. I think I was missing one line to fix the ESC not refocusing initial view.

It still does not work. I've put a breakpoint on all calls to output->focus_view() and saw that after calling this, there is a later call on line 1158 that sets it back.

I've found that adding
```last_focused_view = initial_focus_view;```
on line 536 (before the call to focus_view()) fixes this problem for me and I don't see any bad side effect. But I don't entirely understand the conditions on lines 1141 -- 1144, so this is a guess on my part. It would be great if you could test and reproduce the problem and solution.

Thanks!

**Comment by soreau** [comment]
I see now, I was testing the wrong case. I 'pushed' a new patch to the link. Hopefully this fixes it.

**Comment by dkondor** [comment]
Yes; I just tested, the latest version of the patch fixes this!

**Comment by soreau** [comment]
> It still does not work. I've put a breakpoint on all calls to output->focus_view() and saw that after calling this, there is a later call on line 1158 that sets it back.
> 
> I've found that adding
> `last_focused_view = initial_focus_view;`
> on line 536 (before the call to focus_view()) fixes this problem for me and I don't see any bad side effect. But I don't entirely understand the conditions on lines 1141 -- 1144, so this is a guess on my part. It would be great if you could test and reproduce the problem and solution.

It is clear that this implementation of scale deserves some comments. I will try to add some.

Regarding your findings, this is because without [this](https://github.com/WayfireWM/wayfire/blob/scale/plugins/single_plugins/scale.cpp#L1131-L1155), other code in wayfire will focus a view that isn't the one we are tracking as last_focused_view. (I can't recall the exact cases this happens but you can omit this signal handler (or never connect it) and see what happens.) We have to be careful though because calling focus_view() calls the focus handler and you can possibly get into an infinite loop when calling focus_view from the focus handler. This is why there are so many conditional statements at the beginning of the focus handler.

> 
> Thanks!

**Pull request merged**
