### PR TITLE
output: don't consider minimized views for refocus

### PR DESCRIPTION
**Pull request by soreau**

### CODE REVIEW

**Comment by ammen99** [comment]
Didn't we discuss we should also prevent these views from having cursor focus?

**Comment by soreau** [comment]
Yes but this particular PR is about fixing #522, not about the unrelated issue discussed on IRC.

**Comment by soreau** [comment]
> You can add a check here in this function: https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/input-manager.cpp#L323

This should go in a different PR.

**Comment by ammen99** [comment]
#522 is exactly what I described, please read the issue more carefully :)

**Comment by ammen99** [comment]
But you're right, this is about a different bug. I'll merge this PR (but it doesn't fix #522)

**Pull request merged**
