### PR TITLE
ipc-rules: add focus method for ipc

### PR DESCRIPTION
**Pull request by ssfdust**
* Add window-rules/focus-view method to window-rules plugins
* Add focus method to wayfire_socket.py

### CODE REVIEW

**Comment by ssfdust** [comment]
A simple example that uses wofi to switch between windows with this patch
```Python
#!/bin/env python

import socket
import os
import json as js
import subprocess

def get_msg_template(method: str):
    # Create generic message template
    message = {}
    message["method"] = method
    message["data"] = {}
    return message


class WayfireSocket:
    def __init__(self, socket_name):
        self.client = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.client.connect(socket_name)

    def read_exact(self, n):
        response = bytes()
        while n > 0:
            read_this_time = self.client.recv(n)
            if not read_this_time:
                raise Exception("Failed to read anything from the socket!")
            n -= len(read_this_time)
            response += read_this_time

        return response

    def read_message(self):
        rlen = int.from_bytes(self.read_exact(4), byteorder="little")
        response_message = self.read_exact(rlen)
        return js.loads(response_message)

    def send_json(self, msg):
        data = js.dumps(msg).encode('utf8')
        header = len(data).to_bytes(4, byteorder="little")
        self.client.send(header)
        self.client.send(data)
        return self.read_message()

    def get_views(self):
        message = get_msg_template("stipc/list_views")
        return self.send_json(message)

    def set_focus(self, view_id: int):
        message = get_msg_template("window-rules/focus-view")
        message["data"]["id"] = view_id
        return self.send_json(message)


def main():
    addr = os.getenv('WAYFIRE_SOCKET')
    sock = WayfireSocket(addr)

    windows_map = {}
    for view in sock.get_views():
        if view['layer'] == 'workspace':
            index = view['app-id'] + ' - ' + view['title']
            windows_map[index] = view['id']

    indexs = "\n".join(windows_map.keys()).encode()
    proc = subprocess.Popen(["wofi", "--dmenu"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    window_index = proc.communicate(input=indexs)[0].decode().strip()
    window_id = windows_map[window_index]

    print(sock.set_focus(window_id))

if __name__ == '__main__':
    main()
```

**Review by ammen99 — APPROVED** [review]
Thanks!

**Comment by ammen99** [comment]
> A simple example that uses wofi to switch between windows with this patch


Cool, seems like an interesting idea!

**Comment by ammen99** [comment]
We can merge once the code style is fixed

**Pull request merged**
