### PR TITLE
simplify run() to use daemon(3)

### PR DESCRIPTION
**Pull request by epsilon-0**
Signed-off-by: Aisha Tammy <aisha@bsd.ac>

### CODE REVIEW

**Comment by ammen99** [comment]
This makes it not possible to track the PID of the started process. This doesn't work with dbus-activated apps, true, but it is useful when you know what client you are starting. Can we somehow still pipe the PID to the compositor with `daemon(3)`?

**Comment by epsilon-0** [comment]
I don't see the return value from `run(...)` being used anywhere right now, so the information is lost in any case. It would be easier to log the `command` being run instead of the PID, as the command itself might do some internal daemonize stuff and change PIDs.

**Comment by ammen99** [comment]
> I don't see the return value from `run(...)` being used anywhere right now, so the information is lost in any case. It would be easier to log the `command` being run instead of the PID, as the command itself might do some internal daemonize stuff and change PIDs.

I use it in the scenegraph branch for telling the tests (which call run() via IPC) the PID of the started process. I know it doesn't work for everything, but it does work when you know in advance that the processes you are starting don't do advanced stuff.

**Comment by epsilon-0** [comment]
moved to https://github.com/WayfireWM/wayfire/pull/1596

**Pull request closed without merging**
