### PR TITLE
Check wlr headers for xwayland and display enabled state

### PR DESCRIPTION
**Pull request by soreau**

### CODE REVIEW

**Comment by emersion** [comment]
Better way to do it: https://github.com/swaywm/sway/blob/master/meson.build#L73

**Comment by ammen99** [comment]
I don't understand, is this just a message when compiling? Also I like the one-liner which emersion linked :)

**Comment by soreau** [comment]
@emersion This was a nice change for simplification, thanks. Is there a way to silence the message "Fetching value of define "WLR_HAS_XWAYLAND" with dependency wlroots: 1" in the configure output?

**Comment by emersion** [comment]
>I don't understand, is this just a message when compiling?

If you try building wayfire with xwayland while wlroots has been built without it, you can error out.

>This was a nice change for simplification, thanks. Is there a way to silence the message "Fetching value of define "WLR_HAS_XWAYLAND" with dependency wlroots: 1" in the configure output?

No idea, sorry.

**Comment by ammen99** [comment]
Thanks to both @emersion and @soreau

**Pull request merged**
