### PR TITLE
xwayland: Handle minimize actions

### PR DESCRIPTION
**Pull request by soreau**
This fixes xwayland CSD minimize buttons for clients like steam and chrome.

### CODE REVIEW

**Comment by damianatorrpm** [comment]
well fair enough, I guess I can close my PR than and open two other PR's for the stuff in since I can recreate damianatorrpm/wayfire when no PR depends on it.

This one here seems to fail though:
```
[  124s] ../src/view/xwayland.cpp:341:55: error: ‘data’ was not declared in this scope; did you mean ‘std::data’?
[  124s]   341 |             auto ev = (wlr_xwayland_minimize_event *) data;
[  124s]       |                                                       ^~~~
[  124s]       |                                                       std::data
```

**Comment by kode54** [comment]
Oh, crud, when I was manually fixing that event in the patch file, I forgot to add it as a parameter to the callback. Basically, the minimize callback should be `(void* data)`

**Comment by ammen99** [comment]
LGTM, but I will postpone merging this until we get wayfire 0.5 because the wlroots patch this thing relies on didn't make it to wlroots 0.11 (and wayfire 0.5 should depend on wlroots 0.11, not on wlroots master).

**Comment by ammen99** [comment]
Thanks!

**Pull request merged**
