### PR TITLE
add compositor stages

### LINKED ISSUE #671: wlr_output_layout_output_at assertion prevents restarting after crash
Maybe it's a FreeBSD/ConsoleKit2/amdgpu/the-kind-of-crashes-I-have/??? thing (most likely consolekit2, it doesn't do any fancy vt/kms/etc recovery that logind might be doing??), but this assertion:

https://github.com/WayfireWM/wayfire/blob/0e157a5c418341d2dfbc2c2265a31761d3d8740c/src/core/output-layout.cpp#L1609

is usually not letting me start wayfire again after a hard crash.
For the first few early `get_output_coords_at` calls (that happen before the modesetting has finished), `wlr_output_layout_output_at` is returning NULL because the output's box is `0,0,0,0`.

Just commenting the assert out has helped.

### PR DESCRIPTION
**Pull request by ammen99**
- uncrustify: fix wrongly added newline between enum class and ident
- core: add information about compositor state to API
- core: refresh device mappings after the backend has started

This should fix #671, @myfreeweb do you have a way to verify the crash is fixed?

### CODE REVIEW

**Comment by myfreeweb** [comment]
I can restart a few times in a row if I do it carefully, but looks like it's possible without this patch too.

I can still fail that assertion by moving the mouse while starting Wayfire!

I'm not sure why you decided that it must be the mappings thing rather than real events. I think input processing just should be made to work with no display, including after unplugging an output..

**Comment by ammen99** [comment]
> I can restart a few times in a row if I do it carefully, but looks like it's possible without this patch too.
> 
> I can still fail that assertion by moving the mouse while starting Wayfire!

I thought we don't get input events before the backend is started??

> I'm not sure why you decided that it must be the mappings thing rather than real events. I think input processing just should be made to work with no display, including after unplugging an output..

Yes, it should work with no display, output-layout creates a noop output if no other outputs are connected.

Based on your observations, it seems like Wayfire should simply have some handling to skip any input events before the backends are started.

**Comment by myfreeweb** [comment]
But it's not before backends are started, it's with noop:
https://github.com/WayfireWM/wayfire/issues/671#issuecomment-670510655

> II 07-08-20 16:11:36.218 - [backend/noop/backend.c:16] Starting noop backend
> II 07-08-20 16:11:36.342 - [src/core/seat/input-manager.cpp:75] handle new input: ...
> EE 07-08-20 16:11:36.350 - [types/wlr_output_layout.c:275] output-layout-at 0.000000, 0.000000
> [assert]

**Comment by ammen99** [comment]
> But it's not before backends are started, it's with noop:
> [#671 (comment)](https://github.com/WayfireWM/wayfire/issues/671#issuecomment-670510655)
> 
> > II 07-08-20 16:11:36.218 - [backend/noop/backend.c:16] Starting noop backend
> > II 07-08-20 16:11:36.342 - [src/core/seat/input-manager.cpp:75] handle new input: ...
> > EE 07-08-20 16:11:36.350 - [types/wlr_output_layout.c:275] output-layout-at 0.000000, 0.000000
> > [assert]

The noop backend is started before the noop backend is created, try again with the latest commit.

**Comment by ammen99** [comment]
Note that the crash possibility is still there for touchscreen (for now), but I am working on #256 atm which will change things so that touchscreen events work the same way pointer and touch works.

**Comment by myfreeweb** [comment]
Yes, fixed now.

**Comment by ammen99** [comment]
> Yes, fixed now.

Perfect, thanks for testing.

**Pull request merged**
