### PR TITLE
Track wlroots 0.4

### PR DESCRIPTION
**Pull request by myfreeweb**
Changelog issue over there: https://github.com/swaywm/wlroots/issues/1569

### CODE REVIEW

**Comment by ammen99** [comment]
Yes, makes sense to have such a thing. Do you want to maintain the track-0.4 branch or should we make a `track-wlroots-master` branch in the main repo?

**Comment by myfreeweb** [comment]
Yeah I guess a branch in the main repo would be better

**Comment by ammen99** [comment]
Ok, will create a branch after #163

**Comment by ammen99** [comment]
Maybe we should merge this one considering 0.4 is already out?

**Comment by myfreeweb** [comment]
huh, that was a quick release. yes

**Comment by ammen99** [comment]
Seems to work here (at least the first few times, but that is a "known" issue), thanks!

**Pull request merged**
