### PR TITLE
Track wlroots changes

### PR DESCRIPTION
**Pull request by soreau**

### CODE REVIEW

**Comment by ammen99** [comment]
Duplicate of #121, heh

**Comment by myfreeweb** [comment]
I can drop these from #121

**Comment by ammen99** [comment]
@myfreeweb If you do, we can then directly merge the BSD support without waiting for a wlroots release.

**Comment by myfreeweb** [comment]
done

**Comment by myfreeweb** [comment]
That's https://github.com/soreau/wayfire/pull/2 :)

**Comment by ammen99** [comment]
Taking into account how much we like breakages, here's another one: https://github.com/swaywm/wlroots/pull/1503/

**Comment by myfreeweb** [comment]
heh, that fixes a bug I reported, so that's my "fault" :D https://github.com/soreau/wayfire/pull/3

**Comment by ammen99** [comment]
Guess what, https://github.com/swaywm/wlroots/pull/1513

I can (and will) do that one though, if nobody else wants to :smile:

**Comment by soreau** [comment]
> Note that a list of breaking changes and upgrade paths is available at swaywm/wlroots#1465

@emersion Thanks for creating and sharing this.

**Comment by ammen99** [comment]
@soreau @myfreeweb Thanks, LGTM.

**Pull request merged**
